### ISSUE TITLE
Error uploading image - Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by oim37** [Hounddd/wn-lightgallery-plugin#1]
Hello,

I use winter cms 1.2.1 php v8.  Install plugin - all ok, create category and gallery and try to add image and have error .env not found. Ok i create .env with command 
./artisan winter:env
and have new error "Trying to access array offset on value of type null"
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/4c503bc2-aa45-4921-827a-09696e75f4d6)

**Comment by damsfx** [comment]
@oim37 Can you tell me more : 
- Winter CMS version
- Complete PHP version
- Other plugins installed

Do your logs contain more information about the line number and file where the error occurred?

**Comment by oim37** [comment]
Winter CMS build 1.2.1
PHP 8.0.28 (cli) (built: Feb 14 2023 11:05:44)

+----------------------+---------+-----------------+----------------+
| Plugin name          | Version | Updates enabled | Plugin enabled |
+----------------------+---------+-----------------+----------------+
| Winter.Demo          | 1.0.1   | No              | No             |
+----------------------+---------+-----------------+----------------+
| Winter.Translate     | 2.1.0   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+
| Winter.Pages         | 2.0.2   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+
| Winter.Blog          | 2.0.2   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+
| Winter.Sitemap       | 2.0.0   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+
| Winter.CKEditor      | 1.0.0   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+
| My.Events            | 1.0.1   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+
| Hounddd.lightGallery | 1.0.2   | Yes             | Yes            |
+----------------------+---------+-----------------+----------------+

All other plugins working, when i try upload (check 2 type) have this message:
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/11b6eddc-0b0f-490b-b226-b505c2c0e05f)
Help me to fix this error.

**Comment by oim37** [comment]
Maybe this will help somehow, but logically the problem is similar, only there they add a field in another plugin, and I have a photo. Same error.

https://octobercms.com/plugin/support/shohabbos-customfields/trying-to-access-array-offset-on-value-of-type-null-on-line

**Comment by damsfx** [comment]
I've made a test with no issues: 
```bash
$ php -v
PHP 8.0.20

$ composer show winter/*
winter/storm                 dev-develop 9e0508c
winter/wn-backend-module     dev-develop 8edb044
winter/wn-cms-module         dev-develop 2121f3c
winter/wn-system-module      dev-develop 813234f
...

$ php artisan winter:version
*** Detecting Winter CMS build...
*** We could not accurately determine your Winter CMS build due to the number of modifications. 
*** The closest detected build is Winter CMS build 1.2.1. 

$ composer show hounddd/*
hounddd/wn-lightgallery-plugin dev-main 54ee391
...
```
![Upload](https://github.com/Hounddd/wn-lightgallery-plugin/assets/282242/b0ce3b04-c9c0-454d-a39a-661967b789c6)

**Typically, the data passed to the uploader contains nothing ... a NULL array.**

I've already had this type of case with extensions like "uBlock Origin", but normally it's more on files with a `.json` extension.

You should try to find out if there is a browser extension or software that blocks the sending of data.
You can also open the developer tools of your browser to inspect the POST network request when uploading a file.
In the details of the request you should see the data posted to your server: 

![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/282242/ca10d791-d5cb-41ac-84a2-7b736fab4035)

Then you really have to look at the error in the log of your site in more detail: Backend > eventlogs

**Comment by oim37** [comment]
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/437f06ef-72e5-48c3-b44e-98eb3c177a4b)
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/ce3f2621-147a-4470-b8f6-5769ad5c18d0)

I try with chrome and with egde ..

Upd: In event log last from 13.05.2023 (before i install plugin)

**Comment by oim37** [comment]
I try upload images from base media manager and it working.

**Comment by oim37** [comment]
If i press Ctrl F5 on admin page bkadm/hounddd/lightgallery/galleries i have 1 error, on other plugin pages no showing. May be i need some version of jquery, please say your version. 
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/c4835786-8b04-47a6-956f-4127a0871a6f)

**Comment by damsfx** [comment]
> I try upload images from base media manager and it working.

Good to know.  
I'm surprised that you don't have any errors in the logs.

I've tested it with M Edge  
In the network tab you can this the header for your request :
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/282242/fc5e185b-054b-40de-9120-00f0f6fecc8b)

And int the payload sub-tab, you can see that binaries data are passed to the POST request : 
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/282242/b09d7ca8-fefd-4fe4-9527-5325ac9c6a08)

**The most important is the "400 Bad Request" when calling the upload handler.**  

The plugin just use the default Winter CMS relationships : 
```php
// in Gallery model
/**
 * @var array Attachemnts
 */
public $attachMany = [
    'images' => [
        'System\Models\File',
        'order' => 'sort_order'
    ],
];
```
```yaml
# Gallery model fields.yaml definition
images:
    tab: hounddd.lightgallery::lang.gallery.tabs.images
    label: hounddd.lightgallery::lang.gallery.images
    commentAbove: hounddd.lightgallery::lang.gallery.images_comment
    commentHtml: true
    span: full
    type: fileupload
    mode: image
    imageHeight: 150
    imageWidth: 250
    trigger:
        action: show
        field: complex_mode
        condition: unchecked
```

----

> If i press Ctrl F5 on admin page bkadm/hounddd/lightgallery/galleries i have 1 error, on other plugin pages no showing. May be i need some version of jquery, please say your version

I've got the same error with Sortable in jQuery script.  This may not be related.  
But to get ride of this issue you can update the plugin to the latest version dev-main ([2a3f305](https://github.com/Hounddd/wn-lightgallery-plugin/commit/2a3f305502cc059a41395eac1472abefc0d31bbc) ) 
`composer require hounddd/wn-lightgallery-plugin:dev-main`  
`Upgrading hounddd/wn-lightgallery-plugin (v1.0.1 => dev-main 2a3f305)`

**Comment by oim37** [comment]
I update, error not showing on admin gallery page. But images not uploading, error same. I try upload in created gallery and in new gallery: 
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/66026278-3a5d-4b07-b3f9-45ea34d92e10)
May be we have different winter-min.js.

**Comment by oim37** [comment]
In base media manager all ok 
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/6842168/8d54d890-7e14-42ea-aacc-d274c960c6c9)

**Comment by damsfx** [comment]
@oim37 
> ## 400 Bad Request
> 
> The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).

We got the same Winter's `winter-min.js` file (v 1.2.159)

Try clearing your browser cookies/cache for this site and try again.

**Comment by oim37** [comment]
I send you email, with access in new demo installation. See please..

**Comment by damsfx** [comment]
> I send you email, with access in new demo installation. See please..

I've just successfully uploaded 3 images.   
No errors on my side.

The two latest upload images are screenshots from my Firefox developer tools.  
You can see that I get a status "200" for the upload - not a "400" one.

**Comment by oim37** [comment]
Wow, now i can upload too on test. I create new gallery and it working. I try before after install and he show error. Hm..

**Comment by oim37** [comment]
I find reason, after i install i try and have error and after i setup 777 permissions on "public" in storage/app/uploads. By deafault i have 775 and now i check. Delete created gallery and try to create with 775 permissions and error same. 

I was confused by this error, since usually the message about the rights and I thought that the reason was different.

**Comment by oim37** [comment]
Thank you very much
