### ISSUE TITLE
Limit the number of images displayed by a gallery

### ISSUE THREAD

**Issue by oim37** [Hounddd/wn-lightgallery-plugin#2]
Plugin good, what i need except for one option. As I understood, it is impossible to set the number of displayed photos in the snippet. In total, I have 7 images in the gallery, 3 images fit in a row, and I would like to display only 3 images. Clicking on one of them would open a window where i can view everything of 7.

If it's not difficult, tell me where it can be changed.

**Comment by damsfx** [comment]
@oim37 Like for every Winter CMS plugins components, you can [overide their partials](https://wintercms.com/docs/cms/components#overriding-partials) in your theme.  
 
If you need to limit the amount of images displayed, then you can use the Twig [slice](https://twig.symfony.com/doc/3.x/tags/for.html#iterating-over-a-subset) filter in your component partial :
```twig
{% for image in gallery.images | slice(0, 3) %}
...
{% else %}
    {{ noImagesMessage }}
{% endfor %}
```

**Comment by oim37** [comment]
I meant that make limit for 3 images were displayed in a thumbnail list, but when i clicked, i could see all 7 images.

So it limits the entire gallery to 3.

idea, we have a certain product and a description for it and display all the photos - it takes up a lot of space and is not very beautiful, but 3 is enough and whoever clicks will be able to view the rest.

**Comment by damsfx** [comment]
> I meant that make limit for 3 images were displayed in a thumbnail list, but when i clicked, i could see all 7 images.
> 
> So it limits the entire gallery to 3.
> 
> idea, we have a certain product and a description for it and display all the photos - it takes up a lot of space and is not very beautiful, but 3 is enough and whoever clicks will be able to view the rest.

In this case you have to 
- build all links to images, but hide those after the third loop iteration.  
- use of `data-external-thumb-image` attribute to specify the thumbnail url

Here is an example (using Tailwind CSS) : 
```twig
{% set galleryId = 'lightgallery-'~ random() %}
{% set maxImages = 5 %}

<div class="grid grid-cols-5 grid-rows-4 gap-4" id="{{ galleryId }}" data-lightgallery>
    {% for picture in gallery.images %}
        {% if loop.index == maxImages %}
            <a class="gallery-item aspect-w-1 aspect-h-1 {{ loop.first ? 'col-span-4 row-span-4' }}" href="{{ picture.path }}" target="_blank"
                data-sub-html="<h4>{{ picture.title }}</h4><p>{{ picture.description }}</p>"
                data-external-thumb-image="{{ picture.thumb('400','400',{'mode':'crop'}) }}"
            >
                <img src="{{ picture.thumb('400','400',{'mode':'crop'}) }}" class=" object-cover w-full" alt="{{ picture.title }}">
                <div class=" flex items-center justify-center bg-black/50 text-white">
                    <span class="text-2xl font-semibold">{{ gallery.images | length - 4 }}</span>
                    <svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                </div>
            </a>
        {% else %}
            <a class="gallery-item aspect-w-1 aspect-h-1 {{ loop.first ? 'col-span-4 row-span-4' }} {{ loop.index > maxImages ? 'hidden' }}" href="{{ picture.path }}" target="_blank"
                data-sub-html="<h4>{{ picture.title }}</h4><p>{{ picture.description }}</p>"
                data-external-thumb-image="{{ picture.thumb('400','400',{'mode':'crop'}) }}"
            >
                {% if loop.index < maxImages %}
                <img src="{{ picture.thumb('400','400',{'mode':'crop'}) }}" class=" object-cover w-full" alt="{{ picture.title }}">
                {% endif %}
            </a>
        {% endif %}
    {% else %}
        {{ noImagesMessage }}
    {% endfor %}
</div>
```
It render like this : 
![image](https://github.com/Hounddd/wn-lightgallery-plugin/assets/282242/4640302f-ebb7-466e-bd7e-c76408bc45e9)

**Comment by oim37** [comment]
Thanks for helping me.
